package hu.uni.miskolc.iit.model;

public enum FormTypes{

    RETAKE_EXAM,
    MISSED_HOMEWORK_DEADLINE,
    WRITTEN_EXAMINATION_POSTPONEMENT,
    MISSED_SPECIALIZATION_APPLICATION_DEADLINE,
    INDEX_REPLACEMENT_COST,
    REMEASUREMENT,
    THESIS_POSTPONEMENT,
    FINAL_EXAMINATION_FEE,
    DEAN_ASSIGNMENT,
    RECTOR_ASSIGNMENT,
    REGISTERED_BUT_NOT_APPEARED_ON_EXAM_FEE,
    RETAKE_LECTURE
}